spring:
  datasource:
    url: jdbc:h2:mem:testDB;MODE=MySQLServer
    hikari:
      driverClassName: org.h2.Driver
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672